name: Build and push image

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - docker-image-tag: "latest"
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: bytebase/relay:${{ matrix.docker-image-tag }}
      - name: Image digest
        run: echo "Successfully pushed bytebase/relay:${{ matrix.docker-image-tag }} " ${{ steps.docker_build.outputs.digest }}
